name: Build and Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd myfunction
          docker build -t ${{ secrets.DOCKER_USERNAME }}/azure-functions:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/azure-functions:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/functions-container-action@v1
        with:
          app-name: bahaFunctionApp
          image-name: ${{ secrets.DOCKER_USERNAME }}/azure-functions:latest
          registry-url: docker.io
          registry-username: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }}
